return {
--	"nvim-neo-tree/neo-tree.nvim",
--  cmd = "Neotree",
--  keys = {
--    {
--    "<leader>e",
--      function()
--         require("neo-tree.command").execute({ toggle = true})
--      end,
--      desc = "explore neoTree"
--    }
--  },
--	branch = "v3.x",
--	dependencies = {
--		"nvim-lua/plenary.nvim",
--		"nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
--		"MunifTanjim/nui.nvim",
--		-- "3rd/image.nvim", -- Optional image support in preview window: See `# Preview Mode` for more information
--	},
--	config = function()
--		require("neo-tree").setup({
--			close_if_last_window = true,
--			enable_git_status = true,
--			enable_diagnostics = true,
--		})
--	end,
}
